version: '2'
services:

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'HSE'
      MYSQL_ROOT_PASSWORD: 'letmein'
    ports:
      - '3309:3306'
    expose:
      # open towards container
      - '3309'
      - '3306'
    volumes:
     - ./db:/var/lib/mysql


  pydetect:
    build: ./Detection
    command: python3 single_image_detection.py
    volumes:
      - ./Detection:/usr/app/
      - ./picture:/usr/picture
    expose:
      # unsecured connection, only expose within container
      - '8988'

  website:
    build: ./website
    command: serve -s build
    volumes:
      - ./website:/usr/app/
      - /usr/app/node_modules      
    ports:
      - "9090:5000"
    stdin_open: true


  rest:
    build: ./rest
    command: node -r module-alias/register ./dist --env=development
    volumes:
      - ./rest:/usr/app/
      - /usr/app/node_modules
      - ./picture:/usr/picture
      - ./res:/usr/res
    ports:
      - "9091:3000"
    expose:
      # open towards container
      - "9091"
    stdin_open: true
    depends_on:
      - db
